apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-exporter
spec:
  template:
    spec:
      containers:
        - name: exporter
          env:
            - name: PLEX_ADDR
              value: https://plex.kcloud.zone:32400
            - name: PLEX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: plex-exporter
                  key: token
