package diffx

import (
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"

	"github.com/ianunruh/deploybot/internal/render"
)

func TestHeaderOnlyChange(t *testing.T) {
	t.Parallel()
	before := render.Tree{"app.yaml": []byte("apiVersion: apps/v1\nkind: Deployment\n")}
	after := render.Tree{"app.yaml": []byte("# Generated by deploybot. Do not edit.\napiVersion: apps/v1\nkind: Deployment\n")}
	got := Trees(before, after)
	want := `--- a/app.yaml
+++ b/app.yaml
@@ -1,2 +1,3 @@
+# Generated by deploybot. Do not edit.
 apiVersion: apps/v1
 kind: Deployment
`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Fatal(diff)
	}
}

func TestMiddleChangeKeepsContext(t *testing.T) {
	t.Parallel()
	got := Trees(
		render.Tree{"f": []byte(strings.Repeat("line\n", 8))},
		render.Tree{"f": []byte("line\nline\nchanged\nline\nline\nline\nline\nline\n")},
	)
	if strings.Count(got, "-line") != 1 {
		t.Fatalf("should not rewrite unchanged lines:\n%s", got)
	}
	if !strings.Contains(got, "-line\n+changed\n") {
		t.Fatalf("missing the actual change:\n%s", got)
	}
}

func TestNewAndDeletedFiles(t *testing.T) {
	t.Parallel()
	got := Trees(
		render.Tree{"gone.yaml": []byte("old\n")},
		render.Tree{"new.yaml": []byte("fresh\n")},
	)
	if !strings.Contains(got, "+++ /dev/null\n") || !strings.Contains(got, "-old\n") {
		t.Fatalf("deleted file:\n%s", got)
	}
	if !strings.Contains(got, "+++ b/new.yaml\n") || !strings.Contains(got, "+fresh\n") {
		t.Fatalf("new file:\n%s", got)
	}
}
