package release

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"

	"github.com/ianunruh/deploybot/internal/argo"
	"github.com/ianunruh/deploybot/internal/gitwrite"
	"github.com/ianunruh/deploybot/internal/render"
)

func TestPinDryRunThenApplyAndPromote(t *testing.T) {
	t.Parallel()
	cat := loadExamples(t)
	svc := &Service{Catalog: cat}

	dry, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if !dry.DryRun || dry.Diff == "" {
		t.Fatalf("expected dry-run diff, got %+v", dry)
	}

	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	apply := &Service{
		Catalog: cat,
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}
	pin, err := apply.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc:main-dead@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" || !pin.Synced {
		t.Fatalf("pin %+v", pin)
	}
	if len(pin.Files) != 1 || pin.Files[0] != "k8s/kmc/overlays/homelab/kustomization.yaml" {
		t.Fatalf("pin should only write the homelab overlay, got %v", pin.Files)
	}
	repo, err := git.PlainOpen(dir)
	if err != nil {
		t.Fatal(err)
	}
	pinCommit, err := repo.CommitObject(plumbing.NewHash(pin.Commit))
	if err != nil {
		t.Fatal(err)
	}
	if pinCommit.Message != "pin kmc homelab to ghcr.io/ianunruh/kmc:main-dead" {
		t.Fatalf("pin commit %q", pinCommit.Message)
	}

	tree, err := gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	d, err := cat.Get("kmc")
	if err != nil {
		t.Fatal(err)
	}
	img, err := render.CurrentImage(tree, d, "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if img.Digest != "sha256:abc" {
		t.Fatalf("image %+v", img)
	}

	prom, err := apply.Promote(t.Context(), "kmc", "homelab", "prod", "ghcr.io/ianunruh/kmc:main-dead@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if prom.Commit == "" {
		t.Fatal("missing promote commit")
	}
	promCommit, err := repo.CommitObject(plumbing.NewHash(prom.Commit))
	if err != nil {
		t.Fatal(err)
	}
	if promCommit.Message != "promote kmc homelab -> prod (ghcr.io/ianunruh/kmc:main-dead)" {
		t.Fatalf("promote commit %q", promCommit.Message)
	}
	tree, err = gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	prod, err := render.CurrentImage(tree, d, "prod")
	if err != nil {
		t.Fatal(err)
	}
	if prod != img {
		t.Fatalf("prod %+v want %+v", prod, img)
	}

	keep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(keep) != "KEEPME\n" {
		t.Fatalf("pin/promote must not rewrite workload YAML, got %q", keep)
	}
	sandbox, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(sandbox, []byte("patches:")) || bytes.Contains(sandbox, []byte("Generated by")) {
		t.Fatalf("shared Argo kustomization rewritten:\n%s", sandbox)
	}
	prodKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) {
		t.Fatalf("lost configMapGenerator:\n%s", prodKust)
	}
}

func TestPinWaitsHealthyByDefault(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Progressing", Sync: "OutOfSync"})
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    80 * time.Millisecond,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}
	_, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err == nil || !strings.Contains(err.Error(), "healthy") {
		t.Fatalf("expected wait-healthy error, got %v", err)
	}
}

func TestWithWaitSkipsHealthy(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Progressing", Sync: "OutOfSync"})
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    30 * time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}

	start := time.Now()
	pin, err := svc.WithWait(false).Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if time.Since(start) > 2*time.Second {
		t.Fatal("WithWait(false) should return before the healthy poll")
	}
	if pin.Commit == "" || !pin.Synced {
		t.Fatalf("expected commit and sync trigger, got %+v", pin)
	}
	if len(fake.Synced) != 1 {
		t.Fatalf("Argo sync %v", fake.Synced)
	}
	st, err := fake.Get(t.Context(), "kmc")
	if err != nil {
		t.Fatal(err)
	}
	if st.Health != "Progressing" {
		t.Fatalf("sync should not wait for healthy, got %+v", st)
	}
}

func TestWithSyncSkipArgo(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}

	skip := svc.WithSync(false)
	if skip == svc || skip.Sync {
		t.Fatal("WithSync(false) should copy with Sync off")
	}
	pin, err := skip.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" || pin.Synced {
		t.Fatalf("expected commit without Argo sync, got %+v", pin)
	}
	if len(fake.Synced) != 0 {
		t.Fatalf("Argo synced on opt-out: %v", fake.Synced)
	}

	pin2, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:def")
	if err != nil {
		t.Fatal(err)
	}
	if !pin2.Synced || len(fake.Synced) != 1 {
		t.Fatalf("default pin should still sync Argo: %+v %v", pin2, fake.Synced)
	}

	off := &Service{Sync: false}
	if off.WithSync(true).Sync {
		t.Fatal("WithSync cannot enable Argo when the service has it disabled")
	}
}

func TestPinPush(t *testing.T) {
	t.Parallel()
	cat := loadExamples(t)
	dir := initOpsRepo(t)
	remote := addBareRemote(t, dir)
	branch, before := repoHead(t, dir)
	author := gitwrite.Author{Name: "t", Email: "t@t"}

	localOnly := &Service{Catalog: cat, OpsRepo: dir, Apply: true, Author: author}
	pin, err := localOnly.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:aaa")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Pushed || pin.Ref != "" {
		t.Fatalf("apply without push should stay local: %+v", pin)
	}
	if branchHash(t, remote, branch) != before {
		t.Fatal("remote updated without push")
	}

	withPush := &Service{Catalog: cat, OpsRepo: dir, Apply: true, Push: true, Author: author}
	pin2, err := withPush.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:bbb")
	if err != nil {
		t.Fatal(err)
	}
	if !pin2.Pushed || pin2.Commit == "" {
		t.Fatalf("expected push, got %+v", pin2)
	}
	if pin2.Ref != git.DefaultRemoteName+"/"+branch {
		t.Fatalf("ref %q", pin2.Ref)
	}
	if branchHash(t, remote, branch) != pin2.Commit {
		t.Fatalf("remote %s want %s", branchHash(t, remote, branch), pin2.Commit)
	}
}

func TestPushRequiresApply(t *testing.T) {
	t.Parallel()
	svc := &Service{Catalog: loadExamples(t), Push: true}
	_, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err == nil || !strings.Contains(err.Error(), "push requires apply") {
		t.Fatalf("got %v", err)
	}
}
