package release

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/ianunruh/deploybot/internal/argo"
	"github.com/ianunruh/deploybot/internal/gitwrite"
	"github.com/ianunruh/deploybot/internal/render"
)

func TestReconcileWritesManifestsAndPreservesHumanBits(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	homelab := argo.NewFake()
	homelab.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	prod := argo.NewFake()
	prod.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    stageRouter{"homelab": homelab, "prod": prod},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}

	pin, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" {
		t.Fatal("missing pin commit")
	}

	got, err := svc.Reconcile(t.Context(), "kmc", []string{"homelab"})
	if err != nil {
		t.Fatal(err)
	}
	if got.Commit == "" || !got.Synced {
		t.Fatalf("reconcile %+v", got)
	}
	if len(prod.Synced) != 0 {
		t.Fatalf("prod Argo synced on homelab-only reconcile: %v", prod.Synced)
	}
	if len(homelab.Synced) != 2 { // pin + reconcile
		t.Fatalf("homelab Argo syncs %v", homelab.Synced)
	}

	dep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(dep) == "KEEPME\n" || !bytes.Contains(dep, []byte("kind: Deployment")) {
		t.Fatalf("reconcile should write generated workload YAML, got %q", dep)
	}

	img, err := render.CurrentImage(mustOpenTree(t, dir), mustKMC(t, svc), "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if img.Digest != "sha256:abc" {
		t.Fatalf("reconcile dropped pin %+v", img)
	}

	prodKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) || bytes.Contains(prodKust, []byte("Generated by")) {
		t.Fatalf("homelab-only reconcile rewrote prod overlay:\n%s", prodKust)
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/kmc/overlays/prod/patch-httproute.yaml")); !os.IsNotExist(err) {
		t.Fatal("homelab-only reconcile wrote prod patches")
	}

	app, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kmc.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"kind: Application", "project: sandbox", "k8s/kmc/overlays/homelab", "kmc-system"} {
		if !bytes.Contains(app, []byte(want)) {
			t.Fatalf("missing %q in Application:\n%s", want, app)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/prod/kmc.yaml")); !os.IsNotExist(err) {
		t.Fatal("homelab-only reconcile wrote prod Application")
	}

	sandbox, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(sandbox, []byte("patches:")) || bytes.Contains(sandbox, []byte("Generated by")) {
		t.Fatalf("reconcile rewrote Argo project kustomization:\n%s", sandbox)
	}

	all, err := svc.Reconcile(t.Context(), "kmc", nil)
	if err != nil {
		t.Fatal(err)
	}
	if all.Commit == "" {
		t.Fatal("missing all-stages commit")
	}
	prodApp, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/prod/kmc.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodApp, []byte("k8s/kmc/overlays/prod")) {
		t.Fatalf("prod Application:\n%s", prodApp)
	}
	prodKust, err = os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) {
		t.Fatalf("lost configMapGenerator:\n%s", prodKust)
	}
}

func TestReconcileControllerKeepsHumanPatches(t *testing.T) {
	t.Parallel()
	dir := initControllerOpsRepo(t)
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}
	pin, err := svc.Pin(t.Context(), "kmc-controller", "homelab", "ghcr.io/ianunruh/kmc-controller@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" {
		t.Fatal("missing pin commit")
	}
	got, err := svc.Reconcile(t.Context(), "kmc-controller", []string{"homelab"})
	if err != nil {
		t.Fatal(err)
	}
	if got.Commit == "" {
		t.Fatal("missing reconcile commit")
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/kmc-controller/base/service.yaml")); !os.IsNotExist(err) {
		t.Fatal("controller reconcile wrote a Service")
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/kmc-controller/base/httproute.yaml")); !os.IsNotExist(err) {
		t.Fatal("controller reconcile wrote an HTTPRoute")
	}
	keep := map[string]string{
		"k8s/kmc-controller/base/crds/ipaddresses.yaml":        "kind: CustomResourceDefinition\n",
		"k8s/kmc-controller/base/rbac/service_account.yaml":    "kind: ServiceAccount\n",
		"k8s/kmc-controller/base/patch-manager.yaml":           "kind: Deployment\n",
		"k8s/kmc-controller/overlays/homelab/patch-cidrs.yaml": "kind: Deployment\n",
	}
	for rel, body := range keep {
		got, err := os.ReadFile(filepath.Join(dir, rel))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != body {
			t.Fatalf("%s rewritten: %q", rel, got)
		}
	}
	baseKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc-controller/base/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(baseKust, []byte("crds/ipaddresses.yaml")) || !bytes.Contains(baseKust, []byte("patch-manager.yaml")) {
		t.Fatalf("lost extra base kustomize bits:\n%s", baseKust)
	}
	overlayKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc-controller/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(overlayKust, []byte("patch-cidrs.yaml")) {
		t.Fatalf("lost CIDR patch:\n%s", overlayKust)
	}
	if !bytes.Contains(overlayKust, []byte("sha256:abc")) {
		t.Fatalf("reconcile dropped pin:\n%s", overlayKust)
	}
}

func TestDiffReconcileDoesNotWrite(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	svc := &Service{Catalog: loadExamples(t), OpsRepo: dir, Apply: true}
	mut, err := svc.DiffReconcile(t.Context(), "kmc", []string{"homelab"})
	if err != nil {
		t.Fatal(err)
	}
	if !mut.DryRun || mut.Commit != "" || mut.Diff == "" {
		t.Fatalf("preview %+v", mut)
	}
	keep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(keep) != "KEEPME\n" {
		t.Fatalf("DiffReconcile wrote workload YAML: %q", keep)
	}
}

func TestReconcileUnknownStage(t *testing.T) {
	t.Parallel()
	svc := &Service{Catalog: loadExamples(t)}
	if _, err := svc.Reconcile(t.Context(), "kmc", []string{"nope"}); err == nil {
		t.Fatal("expected error")
	}
}
