package release

import (
	"bytes"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"

	"github.com/ianunruh/deploybot/internal/argo"
	"github.com/ianunruh/deploybot/internal/catalog"
	"github.com/ianunruh/deploybot/internal/gitwrite"
	"github.com/ianunruh/deploybot/internal/render"
	"github.com/ianunruh/deploybot/internal/spec"
)

func TestPinDryRunThenApplyAndPromote(t *testing.T) {
	t.Parallel()
	cat := loadExamples(t)
	svc := &Service{Catalog: cat}

	dry, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if !dry.DryRun || dry.Diff == "" {
		t.Fatalf("expected dry-run diff, got %+v", dry)
	}

	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	apply := &Service{
		Catalog: cat,
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}
	pin, err := apply.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc:main-dead@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" || !pin.Synced {
		t.Fatalf("pin %+v", pin)
	}
	if len(pin.Files) != 1 || pin.Files[0] != "k8s/kmc/overlays/homelab/kustomization.yaml" {
		t.Fatalf("pin should only write the homelab overlay, got %v", pin.Files)
	}

	tree, err := gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	d, err := cat.Get("kmc")
	if err != nil {
		t.Fatal(err)
	}
	img, err := render.CurrentImage(tree, d, "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if img.Digest != "sha256:abc" {
		t.Fatalf("image %+v", img)
	}

	prom, err := apply.Promote(t.Context(), "kmc", "homelab", "prod")
	if err != nil {
		t.Fatal(err)
	}
	if prom.Commit == "" {
		t.Fatal("missing promote commit")
	}
	tree, err = gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	prod, err := render.CurrentImage(tree, d, "prod")
	if err != nil {
		t.Fatal(err)
	}
	if prod != img {
		t.Fatalf("prod %+v want %+v", prod, img)
	}

	keep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(keep) != "KEEPME\n" {
		t.Fatalf("pin/promote must not rewrite workload YAML, got %q", keep)
	}
	sandbox, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(sandbox, []byte("patches:")) || bytes.Contains(sandbox, []byte("Generated by")) {
		t.Fatalf("shared Argo kustomization rewritten:\n%s", sandbox)
	}
	prodKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) {
		t.Fatalf("lost configMapGenerator:\n%s", prodKust)
	}
}

func TestSyncWritesManifestsAndPreservesHumanBits(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	homelab := argo.NewFake()
	homelab.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	prod := argo.NewFake()
	prod.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    stageRouter{"homelab": homelab, "prod": prod},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}

	pin, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" {
		t.Fatal("missing pin commit")
	}

	got, err := svc.SyncManifests(t.Context(), "kmc", []string{"homelab"})
	if err != nil {
		t.Fatal(err)
	}
	if got.Commit == "" || !got.Synced {
		t.Fatalf("sync %+v", got)
	}
	if len(prod.Synced) != 0 {
		t.Fatalf("prod Argo synced on homelab-only sync: %v", prod.Synced)
	}
	if len(homelab.Synced) != 2 { // pin + sync
		t.Fatalf("homelab Argo syncs %v", homelab.Synced)
	}

	dep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(dep) == "KEEPME\n" || !bytes.Contains(dep, []byte("kind: Deployment")) {
		t.Fatalf("sync should write generated workload YAML, got %q", dep)
	}

	img, err := render.CurrentImage(mustOpenTree(t, dir), mustKMC(t, svc), "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if img.Digest != "sha256:abc" {
		t.Fatalf("sync dropped pin %+v", img)
	}

	prodKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) || bytes.Contains(prodKust, []byte("Generated by")) {
		t.Fatalf("homelab-only sync rewrote prod overlay:\n%s", prodKust)
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/kmc/overlays/prod/patch-httproute.yaml")); !os.IsNotExist(err) {
		t.Fatal("homelab-only sync wrote prod patches")
	}

	app, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kmc.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"kind: Application", "project: sandbox", "k8s/kmc/overlays/homelab", "kmc-system"} {
		if !bytes.Contains(app, []byte(want)) {
			t.Fatalf("missing %q in Application:\n%s", want, app)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/prod/kmc.yaml")); !os.IsNotExist(err) {
		t.Fatal("homelab-only sync wrote prod Application")
	}

	sandbox, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(sandbox, []byte("patches:")) || bytes.Contains(sandbox, []byte("Generated by")) {
		t.Fatalf("sync rewrote Argo project kustomization:\n%s", sandbox)
	}

	all, err := svc.SyncManifests(t.Context(), "kmc", nil)
	if err != nil {
		t.Fatal(err)
	}
	if all.Commit == "" {
		t.Fatal("missing all-stages commit")
	}
	prodApp, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/prod/kmc.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodApp, []byte("k8s/kmc/overlays/prod")) {
		t.Fatalf("prod Application:\n%s", prodApp)
	}
	prodKust, err = os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) {
		t.Fatalf("lost configMapGenerator:\n%s", prodKust)
	}
}

func TestSyncUnknownStage(t *testing.T) {
	t.Parallel()
	svc := &Service{Catalog: loadExamples(t)}
	if _, err := svc.SyncManifests(t.Context(), "kmc", []string{"nope"}); err == nil {
		t.Fatal("expected error")
	}
}

type stageRouter map[string]argo.Client

func (r stageRouter) ForStage(stage string) argo.Client { return r[stage] }

func mustOpenTree(t *testing.T, dir string) render.Tree {
	t.Helper()
	tree, err := gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	return tree
}

func mustKMC(t *testing.T, svc *Service) *spec.Deployable {
	t.Helper()
	d, err := svc.Catalog.Get("kmc")
	if err != nil {
		t.Fatal(err)
	}
	return d
}

func loadExamples(t *testing.T) *catalog.Catalog {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	root := filepath.Join(filepath.Dir(file), "..", "..", "examples")
	cat, err := catalog.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	return cat
}

func initOpsRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	repo, err := git.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"README":                       "ops\n",
		"k8s/kmc/base/deployment.yaml": "KEEPME\n",
		"k8s/kmc/overlays/homelab/kustomization.yaml": "resources:\n  - ../../base\n",
		"k8s/kmc/overlays/prod/kustomization.yaml": `resources:
  - ../../base
configMapGenerator:
  - name: kmc-env
    envs:
      - config.env
`,
		"k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml": `resources:
  - ../../base
patches:
  - path: kmc.yaml
`,
	}
	for rel, body := range files {
		fp := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(fp), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fp, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := wt.Add(rel); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := wt.Commit("init", &git.CommitOptions{
		Author: &object.Signature{Name: "t", Email: "t@t", When: time.Now()},
	}); err != nil {
		t.Fatal(err)
	}
	return dir
}
