package release

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/config"
	"github.com/go-git/go-git/v5/plumbing"
	"github.com/go-git/go-git/v5/plumbing/object"

	"github.com/ianunruh/deploybot/internal/argo"
	"github.com/ianunruh/deploybot/internal/catalog"
	"github.com/ianunruh/deploybot/internal/gitwrite"
	"github.com/ianunruh/deploybot/internal/image"
	"github.com/ianunruh/deploybot/internal/render"
	"github.com/ianunruh/deploybot/internal/spec"
)

func TestPinDryRunThenApplyAndPromote(t *testing.T) {
	t.Parallel()
	cat := loadExamples(t)
	svc := &Service{Catalog: cat}

	dry, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if !dry.DryRun || dry.Diff == "" {
		t.Fatalf("expected dry-run diff, got %+v", dry)
	}

	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	apply := &Service{
		Catalog: cat,
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}
	pin, err := apply.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc:main-dead@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" || !pin.Synced {
		t.Fatalf("pin %+v", pin)
	}
	if len(pin.Files) != 1 || pin.Files[0] != "k8s/kmc/overlays/homelab/kustomization.yaml" {
		t.Fatalf("pin should only write the homelab overlay, got %v", pin.Files)
	}
	repo, err := git.PlainOpen(dir)
	if err != nil {
		t.Fatal(err)
	}
	pinCommit, err := repo.CommitObject(plumbing.NewHash(pin.Commit))
	if err != nil {
		t.Fatal(err)
	}
	if pinCommit.Message != "pin kmc homelab to ghcr.io/ianunruh/kmc:main-dead" {
		t.Fatalf("pin commit %q", pinCommit.Message)
	}

	tree, err := gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	d, err := cat.Get("kmc")
	if err != nil {
		t.Fatal(err)
	}
	img, err := render.CurrentImage(tree, d, "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if img.Digest != "sha256:abc" {
		t.Fatalf("image %+v", img)
	}

	prom, err := apply.Promote(t.Context(), "kmc", "homelab", "prod")
	if err != nil {
		t.Fatal(err)
	}
	if prom.Commit == "" {
		t.Fatal("missing promote commit")
	}
	promCommit, err := repo.CommitObject(plumbing.NewHash(prom.Commit))
	if err != nil {
		t.Fatal(err)
	}
	if promCommit.Message != "promote kmc homelab -> prod (ghcr.io/ianunruh/kmc:main-dead)" {
		t.Fatalf("promote commit %q", promCommit.Message)
	}
	tree, err = gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	prod, err := render.CurrentImage(tree, d, "prod")
	if err != nil {
		t.Fatal(err)
	}
	if prod != img {
		t.Fatalf("prod %+v want %+v", prod, img)
	}

	keep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(keep) != "KEEPME\n" {
		t.Fatalf("pin/promote must not rewrite workload YAML, got %q", keep)
	}
	sandbox, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(sandbox, []byte("patches:")) || bytes.Contains(sandbox, []byte("Generated by")) {
		t.Fatalf("shared Argo kustomization rewritten:\n%s", sandbox)
	}
	prodKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) {
		t.Fatalf("lost configMapGenerator:\n%s", prodKust)
	}
}

func TestReconcileWritesManifestsAndPreservesHumanBits(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	homelab := argo.NewFake()
	homelab.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	prod := argo.NewFake()
	prod.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    stageRouter{"homelab": homelab, "prod": prod},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}

	pin, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" {
		t.Fatal("missing pin commit")
	}

	got, err := svc.Reconcile(t.Context(), "kmc", []string{"homelab"})
	if err != nil {
		t.Fatal(err)
	}
	if got.Commit == "" || !got.Synced {
		t.Fatalf("reconcile %+v", got)
	}
	if len(prod.Synced) != 0 {
		t.Fatalf("prod Argo synced on homelab-only reconcile: %v", prod.Synced)
	}
	if len(homelab.Synced) != 2 { // pin + reconcile
		t.Fatalf("homelab Argo syncs %v", homelab.Synced)
	}

	dep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(dep) == "KEEPME\n" || !bytes.Contains(dep, []byte("kind: Deployment")) {
		t.Fatalf("reconcile should write generated workload YAML, got %q", dep)
	}

	img, err := render.CurrentImage(mustOpenTree(t, dir), mustKMC(t, svc), "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if img.Digest != "sha256:abc" {
		t.Fatalf("reconcile dropped pin %+v", img)
	}

	prodKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) || bytes.Contains(prodKust, []byte("Generated by")) {
		t.Fatalf("homelab-only reconcile rewrote prod overlay:\n%s", prodKust)
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/kmc/overlays/prod/patch-httproute.yaml")); !os.IsNotExist(err) {
		t.Fatal("homelab-only reconcile wrote prod patches")
	}

	app, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kmc.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"kind: Application", "project: sandbox", "k8s/kmc/overlays/homelab", "kmc-system"} {
		if !bytes.Contains(app, []byte(want)) {
			t.Fatalf("missing %q in Application:\n%s", want, app)
		}
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/prod/kmc.yaml")); !os.IsNotExist(err) {
		t.Fatal("homelab-only reconcile wrote prod Application")
	}

	sandbox, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(sandbox, []byte("patches:")) || bytes.Contains(sandbox, []byte("Generated by")) {
		t.Fatalf("reconcile rewrote Argo project kustomization:\n%s", sandbox)
	}

	all, err := svc.Reconcile(t.Context(), "kmc", nil)
	if err != nil {
		t.Fatal(err)
	}
	if all.Commit == "" {
		t.Fatal("missing all-stages commit")
	}
	prodApp, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/prod/kmc.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodApp, []byte("k8s/kmc/overlays/prod")) {
		t.Fatalf("prod Application:\n%s", prodApp)
	}
	prodKust, err = os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) {
		t.Fatalf("lost configMapGenerator:\n%s", prodKust)
	}
}

func TestReconcileControllerKeepsHumanPatches(t *testing.T) {
	t.Parallel()
	dir := initControllerOpsRepo(t)
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}
	pin, err := svc.Pin(t.Context(), "kmc-controller", "homelab", "ghcr.io/ianunruh/kmc-controller@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" {
		t.Fatal("missing pin commit")
	}
	got, err := svc.Reconcile(t.Context(), "kmc-controller", []string{"homelab"})
	if err != nil {
		t.Fatal(err)
	}
	if got.Commit == "" {
		t.Fatal("missing reconcile commit")
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/kmc-controller/base/service.yaml")); !os.IsNotExist(err) {
		t.Fatal("controller reconcile wrote a Service")
	}
	if _, err := os.Stat(filepath.Join(dir, "k8s/kmc-controller/base/httproute.yaml")); !os.IsNotExist(err) {
		t.Fatal("controller reconcile wrote an HTTPRoute")
	}
	keep := map[string]string{
		"k8s/kmc-controller/base/crds/ipaddresses.yaml":        "kind: CustomResourceDefinition\n",
		"k8s/kmc-controller/base/rbac/service_account.yaml":    "kind: ServiceAccount\n",
		"k8s/kmc-controller/base/patch-manager.yaml":           "kind: Deployment\n",
		"k8s/kmc-controller/overlays/homelab/patch-cidrs.yaml": "kind: Deployment\n",
	}
	for rel, body := range keep {
		got, err := os.ReadFile(filepath.Join(dir, rel))
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != body {
			t.Fatalf("%s rewritten: %q", rel, got)
		}
	}
	baseKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc-controller/base/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(baseKust, []byte("crds/ipaddresses.yaml")) || !bytes.Contains(baseKust, []byte("patch-manager.yaml")) {
		t.Fatalf("lost extra base kustomize bits:\n%s", baseKust)
	}
	overlayKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc-controller/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(overlayKust, []byte("patch-cidrs.yaml")) {
		t.Fatalf("lost CIDR patch:\n%s", overlayKust)
	}
	if !bytes.Contains(overlayKust, []byte("sha256:abc")) {
		t.Fatalf("reconcile dropped pin:\n%s", overlayKust)
	}
}

func TestDiffReconcileDoesNotWrite(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	svc := &Service{Catalog: loadExamples(t), OpsRepo: dir, Apply: true}
	mut, err := svc.DiffReconcile("kmc", []string{"homelab"})
	if err != nil {
		t.Fatal(err)
	}
	if !mut.DryRun || mut.Commit != "" || mut.Diff == "" {
		t.Fatalf("preview %+v", mut)
	}
	keep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(keep) != "KEEPME\n" {
		t.Fatalf("DiffReconcile wrote workload YAML: %q", keep)
	}
}

func TestStatusLinksAndArgoURL(t *testing.T) {
	t.Parallel()
	homelab := argo.NewFake()
	homelab.UIBase = "https://argo.kcloud.zone"
	homelab.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	prod := argo.NewFake()
	prod.UIBase = "https://argo.kcloud.io"
	prod.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	svc := &Service{
		Catalog: loadExamples(t),
		Argo:    stageRouter{"homelab": homelab, "prod": prod},
		Sync:    true,
	}
	st, err := svc.Status(t.Context(), "kmc")
	if err != nil {
		t.Fatal(err)
	}
	if !st.Sync {
		t.Fatalf("expected sync flag, got %+v", st)
	}
	if st.RepoURL != "https://github.com/ianunruh/kmc" {
		t.Fatalf("repo %q", st.RepoURL)
	}
	if st.ProjectURL != "https://trello.com/b/rPALXxJF/kcloud" {
		t.Fatalf("project %q", st.ProjectURL)
	}
	if len(st.Stages) != 2 {
		t.Fatalf("stages %+v", st.Stages)
	}
	if st.Stages[0].ArgoURL != "https://argo.kcloud.zone/applications/kmc" {
		t.Fatalf("homelab argo %q", st.Stages[0].ArgoURL)
	}
	if st.Stages[1].ArgoURL != "https://argo.kcloud.io/applications/kmc" {
		t.Fatalf("prod argo %q", st.Stages[1].ArgoURL)
	}
	if st.Stages[0].HeadlampURL == "" || st.Stages[0].GrafanaURL == "" || st.Stages[0].LogsURL == "" {
		t.Fatalf("homelab observability %+v", st.Stages[0])
	}
	if st.Stages[1].HeadlampURL == "" || st.Stages[1].GrafanaURL == "" || st.Stages[1].LogsURL != "" {
		t.Fatalf("prod observability %+v", st.Stages[1])
	}
	assertURL(t, "status headlamp", st.Stages[0].HeadlampURL, "https://headlamp.k8s.kcloud.zone/c/main/deployments?namespace=kmc-system")
	assertURL(t, "status grafana", st.Stages[1].GrafanaURL, "https://grafana.k8s.kcloud.io/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?from=now-1h&to=now&var-namespace=kmc-system")
}

func TestListImages(t *testing.T) {
	t.Parallel()
	cat := loadExamples(t)
	svc := &Service{
		Catalog: cat,
		Images: fakeImages{listing: image.Listing{
			Source: "ghcr",
			Versions: []image.Version{{
				Repository: "ghcr.io/ianunruh/kmc",
				Ref:        "ghcr.io/ianunruh/kmc:main-b8e5098@sha256:abc",
				Tag:        "main-b8e5098",
			}},
		}},
	}
	got, err := svc.ListImages(t.Context(), "kmc")
	if err != nil {
		t.Fatal(err)
	}
	if got.Source != "ghcr" || got.Repository != "ghcr.io/ianunruh/kmc" || len(got.Images) != 1 {
		t.Fatalf("%+v", got)
	}
	if _, err := svc.ListImages(t.Context(), "nope"); err == nil {
		t.Fatal("expected unknown deployable")
	}
	if _, err := (&Service{Catalog: cat}).ListImages(t.Context(), "kmc"); err == nil {
		t.Fatal("expected unconfigured listing")
	}
}

type fakeImages struct {
	listing image.Listing
	err     error
}

func (f fakeImages) List(_ context.Context, _ string, _ string) (image.Listing, error) {
	return f.listing, f.err
}

func TestReconcileUnknownStage(t *testing.T) {
	t.Parallel()
	svc := &Service{Catalog: loadExamples(t)}
	if _, err := svc.Reconcile(t.Context(), "kmc", []string{"nope"}); err == nil {
		t.Fatal("expected error")
	}
}

func TestWithSyncSkipArgo(t *testing.T) {
	t.Parallel()
	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	svc := &Service{
		Catalog: loadExamples(t),
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}

	skip := svc.WithSync(false)
	if skip == svc || skip.Sync {
		t.Fatal("WithSync(false) should copy with Sync off")
	}
	pin, err := skip.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" || pin.Synced {
		t.Fatalf("expected commit without Argo sync, got %+v", pin)
	}
	if len(fake.Synced) != 0 {
		t.Fatalf("Argo synced on opt-out: %v", fake.Synced)
	}

	pin2, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:def")
	if err != nil {
		t.Fatal(err)
	}
	if !pin2.Synced || len(fake.Synced) != 1 {
		t.Fatalf("default pin should still sync Argo: %+v %v", pin2, fake.Synced)
	}

	off := &Service{Sync: false}
	if off.WithSync(true).Sync {
		t.Fatal("WithSync cannot enable Argo when the service has it disabled")
	}
}

func TestPinPush(t *testing.T) {
	t.Parallel()
	cat := loadExamples(t)
	dir := initOpsRepo(t)
	remote := addBareRemote(t, dir)
	branch, before := repoHead(t, dir)
	author := gitwrite.Author{Name: "t", Email: "t@t"}

	localOnly := &Service{Catalog: cat, OpsRepo: dir, Apply: true, Author: author}
	pin, err := localOnly.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:aaa")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Pushed || pin.Ref != "" {
		t.Fatalf("apply without push should stay local: %+v", pin)
	}
	if branchHash(t, remote, branch) != before {
		t.Fatal("remote updated without push")
	}

	withPush := &Service{Catalog: cat, OpsRepo: dir, Apply: true, Push: true, Author: author}
	pin2, err := withPush.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:bbb")
	if err != nil {
		t.Fatal(err)
	}
	if !pin2.Pushed || pin2.Commit == "" {
		t.Fatalf("expected push, got %+v", pin2)
	}
	if pin2.Ref != git.DefaultRemoteName+"/"+branch {
		t.Fatalf("ref %q", pin2.Ref)
	}
	if branchHash(t, remote, branch) != pin2.Commit {
		t.Fatalf("remote %s want %s", branchHash(t, remote, branch), pin2.Commit)
	}
}

func TestPushRequiresApply(t *testing.T) {
	t.Parallel()
	svc := &Service{Catalog: loadExamples(t), Push: true}
	_, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err == nil || !strings.Contains(err.Error(), "push requires apply") {
		t.Fatalf("got %v", err)
	}
}

type stageRouter map[string]argo.Client

func (r stageRouter) ForStage(stage string) argo.Client { return r[stage] }

func mustOpenTree(t *testing.T, dir string) render.Tree {
	t.Helper()
	tree, err := gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	return tree
}

func mustKMC(t *testing.T, svc *Service) *spec.Deployable {
	t.Helper()
	d, err := svc.Catalog.Get("kmc")
	if err != nil {
		t.Fatal(err)
	}
	return d
}

func loadExamples(t *testing.T) *catalog.Catalog {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	root := filepath.Join(filepath.Dir(file), "..", "..", "examples")
	cat, err := catalog.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	return cat
}

func initOpsRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	repo, err := git.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"README":                       "ops\n",
		"k8s/kmc/base/deployment.yaml": "KEEPME\n",
		"k8s/kmc/overlays/homelab/kustomization.yaml": "resources:\n  - ../../base\n",
		"k8s/kmc/overlays/prod/kustomization.yaml": `resources:
  - ../../base
configMapGenerator:
  - name: kmc-env
    envs:
      - config.env
`,
		"k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml": `resources:
  - ../../base
patches:
  - path: kmc.yaml
`,
	}
	for rel, body := range files {
		fp := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(fp), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fp, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := wt.Add(rel); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := wt.Commit("init", &git.CommitOptions{
		Author: &object.Signature{Name: "t", Email: "t@t", When: time.Now()},
	}); err != nil {
		t.Fatal(err)
	}
	return dir
}

func addBareRemote(t *testing.T, local string) string {
	t.Helper()
	remote := filepath.Join(t.TempDir(), "origin.git")
	if _, err := git.PlainInit(remote, true); err != nil {
		t.Fatal(err)
	}
	repo, err := git.PlainOpen(local)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := repo.CreateRemote(&config.RemoteConfig{
		Name: git.DefaultRemoteName,
		URLs: []string{remote},
	}); err != nil {
		t.Fatal(err)
	}
	if err := repo.Push(&git.PushOptions{RemoteName: git.DefaultRemoteName}); err != nil {
		t.Fatal(err)
	}
	return remote
}

func repoHead(t *testing.T, dir string) (branch, hash string) {
	t.Helper()
	repo, err := git.PlainOpen(dir)
	if err != nil {
		t.Fatal(err)
	}
	head, err := repo.Head()
	if err != nil {
		t.Fatal(err)
	}
	return head.Name().Short(), head.Hash().String()
}

func branchHash(t *testing.T, repoDir, branch string) string {
	t.Helper()
	repo, err := git.PlainOpen(repoDir)
	if err != nil {
		t.Fatal(err)
	}
	ref, err := repo.Reference(plumbing.NewBranchReferenceName(branch), true)
	if err != nil {
		t.Fatal(err)
	}
	return ref.Hash().String()
}

func initControllerOpsRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	repo, err := git.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"README": "ops\n",
		"k8s/kmc-controller/base/kustomization.yaml": `resources:
  - deployment.yaml
  - crds/ipaddresses.yaml
  - rbac/service_account.yaml
patches:
  - path: patch-manager.yaml
`,
		"k8s/kmc-controller/base/crds/ipaddresses.yaml":     "kind: CustomResourceDefinition\n",
		"k8s/kmc-controller/base/rbac/service_account.yaml": "kind: ServiceAccount\n",
		"k8s/kmc-controller/base/patch-manager.yaml":        "kind: Deployment\n",
		"k8s/kmc-controller/overlays/homelab/kustomization.yaml": `resources:
  - ../../base
patches:
  - path: patch-cidrs.yaml
`,
		"k8s/kmc-controller/overlays/homelab/patch-cidrs.yaml": "kind: Deployment\n",
	}
	for rel, body := range files {
		fp := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(fp), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fp, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := wt.Add(rel); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := wt.Commit("init", &git.CommitOptions{
		Author: &object.Signature{Name: "t", Email: "t@t", When: time.Now()},
	}); err != nil {
		t.Fatal(err)
	}
	return dir
}
