package release

import (
	"bytes"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"

	"github.com/ianunruh/deploybot/internal/argo"
	"github.com/ianunruh/deploybot/internal/catalog"
	"github.com/ianunruh/deploybot/internal/gitwrite"
	"github.com/ianunruh/deploybot/internal/render"
)

func TestPinDryRunThenApplyAndPromote(t *testing.T) {
	t.Parallel()
	cat := loadExamples(t)
	svc := &Service{Catalog: cat}

	dry, err := svc.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if !dry.DryRun || dry.Diff == "" {
		t.Fatalf("expected dry-run diff, got %+v", dry)
	}

	dir := initOpsRepo(t)
	fake := argo.NewFake()
	fake.Set("kmc", argo.Status{Health: "Healthy", Sync: "Synced"})
	apply := &Service{
		Catalog: cat,
		OpsRepo: dir,
		Apply:   true,
		Sync:    true,
		Argo:    argo.StaticRouter{Client: fake},
		Wait:    time.Second,
		Author:  gitwrite.Author{Name: "t", Email: "t@t"},
	}
	pin, err := apply.Pin(t.Context(), "kmc", "homelab", "ghcr.io/ianunruh/kmc:main-dead@sha256:abc")
	if err != nil {
		t.Fatal(err)
	}
	if pin.Commit == "" || !pin.Synced {
		t.Fatalf("pin %+v", pin)
	}
	if len(pin.Files) != 1 || pin.Files[0] != "k8s/kmc/overlays/homelab/kustomization.yaml" {
		t.Fatalf("pin should only write the homelab overlay, got %v", pin.Files)
	}

	tree, err := gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	d, err := cat.Get("kmc")
	if err != nil {
		t.Fatal(err)
	}
	img, err := render.CurrentImage(tree, d, "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if img.Digest != "sha256:abc" {
		t.Fatalf("image %+v", img)
	}

	prom, err := apply.Promote(t.Context(), "kmc", "homelab", "prod")
	if err != nil {
		t.Fatal(err)
	}
	if prom.Commit == "" {
		t.Fatal("missing promote commit")
	}
	tree, err = gitwrite.OpenTree(dir)
	if err != nil {
		t.Fatal(err)
	}
	prod, err := render.CurrentImage(tree, d, "prod")
	if err != nil {
		t.Fatal(err)
	}
	if prod != img {
		t.Fatalf("prod %+v want %+v", prod, img)
	}

	keep, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/base/deployment.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(keep) != "KEEPME\n" {
		t.Fatalf("pin/promote must not rewrite workload YAML, got %q", keep)
	}
	sandbox, err := os.ReadFile(filepath.Join(dir, "k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(sandbox, []byte("patches:")) || bytes.Contains(sandbox, []byte("Generated by")) {
		t.Fatalf("shared Argo kustomization rewritten:\n%s", sandbox)
	}
	prodKust, err := os.ReadFile(filepath.Join(dir, "k8s/kmc/overlays/prod/kustomization.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(prodKust, []byte("kmc-env")) {
		t.Fatalf("lost configMapGenerator:\n%s", prodKust)
	}
}

func loadExamples(t *testing.T) *catalog.Catalog {
	t.Helper()
	_, file, _, _ := runtime.Caller(0)
	root := filepath.Join(filepath.Dir(file), "..", "..", "examples")
	cat, err := catalog.Load(root)
	if err != nil {
		t.Fatal(err)
	}
	return cat
}

func initOpsRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	repo, err := git.PlainInit(dir, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"README":                       "ops\n",
		"k8s/kmc/base/deployment.yaml": "KEEPME\n",
		"k8s/kmc/overlays/homelab/kustomization.yaml": "resources:\n  - ../../base\n",
		"k8s/kmc/overlays/prod/kustomization.yaml": `resources:
  - ../../base
configMapGenerator:
  - name: kmc-env
    envs:
      - config.env
`,
		"k8s/apps/projects/sandbox/overlays/homelab/kustomization.yaml": `resources:
  - ../../base
patches:
  - path: kmc.yaml
`,
	}
	for rel, body := range files {
		fp := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(fp), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(fp, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := wt.Add(rel); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := wt.Commit("init", &git.CommitOptions{
		Author: &object.Signature{Name: "t", Email: "t@t", When: time.Now()},
	}); err != nil {
		t.Fatal(err)
	}
	return dir
}
