package yamlx

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"
)

const generatedComment = "# Generated by deploybot. Do not edit.\n"

func Marshal(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		return nil, fmt.Errorf("yaml encode: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("yaml close: %w", err)
	}
	return buf.Bytes(), nil
}

func MarshalGenerated(v any) ([]byte, error) {
	b, err := Marshal(v)
	if err != nil {
		return nil, err
	}
	out := make([]byte, 0, len(generatedComment)+len(b))
	out = append(out, generatedComment...)
	out = append(out, b...)
	return out, nil
}

func Unmarshal(b []byte, v any) error {
	return yaml.Unmarshal(b, v)
}
