package render

import (
	"strings"
	"testing"

	"github.com/ianunruh/deploybot/internal/image"
)

func TestPinOverlayPreservesHumanFields(t *testing.T) {
	t.Parallel()
	existing := []byte(`# keep this comment
resources:
  - ../../base
configMapGenerator:
  - name: kmc-env
    envs:
      - config.env
patches:
  - path: patch-httproute.yaml
`)
	out, err := PinOverlay(existing, "ghcr.io/ianunruh/kmc", image.MustParse("ghcr.io/ianunruh/kmc:main-abc"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	for _, want := range []string{
		"configMapGenerator:",
		"kmc-env",
		"patch-httproute.yaml",
		"../../base",
		"newTag: main-abc",
		"name: ghcr.io/ianunruh/kmc",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("missing %q in:\n%s", want, s)
		}
	}
	if strings.Contains(s, "Generated by deploybot") {
		t.Fatalf("pin must not claim mixed overlays: %s", s)
	}
}

func TestPinIsOnlyOverlayImageDiff(t *testing.T) {
	t.Parallel()
	d := loadExample(t, "kmc")
	before, err := Render(d)
	if err != nil {
		t.Fatal(err)
	}
	after, err := Render(d)
	if err != nil {
		t.Fatal(err)
	}
	ref := image.MustParse("ghcr.io/ianunruh/kmc:main-abc123@sha256:deadbeef")
	if err := Pin(after, d, "homelab", ref); err != nil {
		t.Fatal(err)
	}
	changed := 0
	for _, p := range SortedPaths(after) {
		if string(before[p]) == string(after[p]) {
			continue
		}
		changed++
		if p != OverlayKustomizationPath(d, "homelab") {
			t.Fatalf("pin changed unexpected file %s", p)
		}
	}
	if changed != 1 {
		t.Fatalf("pin changed %d files, want 1", changed)
	}
	got, err := CurrentImage(after, d, "homelab")
	if err != nil {
		t.Fatal(err)
	}
	if got != ref {
		t.Fatalf("current image %+v want %+v", got, ref)
	}
}
