package render

import (
	"strings"
	"testing"

	"github.com/ianunruh/deploybot/internal/image"
)

func TestPinOverlayPreservesHumanFields(t *testing.T) {
	t.Parallel()
	existing := []byte(`# keep this comment
resources:
  - ../../base
configMapGenerator:
  - name: kmc-env
    envs:
      - config.env
patches:
  - path: patch-httproute.yaml
`)
	out, err := PinOverlay(existing, "ghcr.io/ianunruh/kmc", image.MustParse("ghcr.io/ianunruh/kmc:main-abc"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	for _, want := range []string{
		"configMapGenerator:",
		"kmc-env",
		"patch-httproute.yaml",
		"../../base",
		"newTag: main-abc",
		"name: ghcr.io/ianunruh/kmc",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("missing %q in:\n%s", want, s)
		}
	}
	if strings.Contains(s, "Generated by deploybot") {
		t.Fatalf("pin must not claim mixed overlays: %s", s)
	}
}

func TestKMCOmitsPodWiring(t *testing.T) {
	t.Parallel()
	d := loadExample(t, "kmc")
	tree, err := Render(d)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := tree["k8s/kmc/overlays/prod/patch-volumes.yaml"]; ok {
		t.Fatal("render must not emit patch-volumes.yaml")
	}
	dep := string(tree["k8s/kmc/base/deployment.yaml"])
	for _, refuse := range []string{"envFrom:", "KMC_CLUSTERS_CONFIG", "volumeMounts:", "kmc-clusters", "cluster-tokens"} {
		if strings.Contains(dep, refuse) {
			t.Fatalf("generated deployment must not include %q:\n%s", refuse, dep)
		}
	}
	prodKust := string(tree["k8s/kmc/overlays/prod/kustomization.yaml"])
	if strings.Contains(prodKust, "patch-volumes.yaml") {
		t.Fatalf("prod overlay must not list volume patch:\n%s", prodKust)
	}
}
