package render

import (
	"strings"
	"testing"

	"github.com/ianunruh/deploybot/internal/image"
)

func TestPinOverlayPreservesHumanFields(t *testing.T) {
	t.Parallel()
	existing := []byte(`# keep this comment
resources:
  - ../../base
configMapGenerator:
  - name: kmc-env
    envs:
      - config.env
patches:
  - path: patch-httproute.yaml
`)
	out, err := PinOverlay(existing, "ghcr.io/ianunruh/kmc", image.MustParse("ghcr.io/ianunruh/kmc:main-abc"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(out)
	for _, want := range []string{
		"configMapGenerator:",
		"kmc-env",
		"patch-httproute.yaml",
		"../../base",
		"newTag: main-abc",
		"name: ghcr.io/ianunruh/kmc",
	} {
		if !strings.Contains(s, want) {
			t.Fatalf("missing %q in:\n%s", want, s)
		}
	}
	if strings.Contains(s, "Generated by deploybot") {
		t.Fatalf("pin must not claim mixed overlays: %s", s)
	}
}

func TestVolumePatchOmitsReplicasAndImage(t *testing.T) {
	t.Parallel()
	d := loadKMC(t)
	tree, err := Render(d)
	if err != nil {
		t.Fatal(err)
	}
	b := tree["k8s/kmc/overlays/prod/patch-volumes.yaml"]
	s := string(b)
	if strings.Contains(s, "replicas:") {
		t.Fatalf("volume patch must not set replicas:\n%s", s)
	}
	if strings.Contains(s, "image:") {
		t.Fatalf("volume patch must not set image:\n%s", s)
	}
	if !strings.Contains(s, "cluster-tokens") {
		t.Fatalf("missing volume:\n%s", s)
	}
}
